// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY2RidKo8Q8ZvrlGLHJBJ2XbFNUd8w9H0',
    appId: '1:736087562902:web:e1f03a01c1a171fd8e40b7',
    messagingSenderId: '736087562902',
    projectId: 'interior-project-b5a35',
    authDomain: 'interior-project-b5a35.firebaseapp.com',
    storageBucket: 'interior-project-b5a35.firebasestorage.app',
    measurementId: 'G-L9GJ4WD19V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wU5x6ZnQX4DigQFDnmPmfSVScCmQtI0',
    appId: '1:736087562902:android:1b6bf9bd1f45ecfe8e40b7',
    messagingSenderId: '736087562902',
    projectId: 'interior-project-b5a35',
    storageBucket: 'interior-project-b5a35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWjxqXN5V2jZ5ZlZFrok3U5rd_3IRcOM',
    appId: '1:736087562902:ios:e381ff60fa6d80de8e40b7',
    messagingSenderId: '736087562902',
    projectId: 'interior-project-b5a35',
    storageBucket: 'interior-project-b5a35.firebasestorage.app',
    // Xcode Runner PRODUCT_BUNDLE_IDENTIFIER 와 동일해야 APNs·FCM 이 정상 동작합니다.
    iosBundleId: 'com.example.interior-workcost-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwWjxqXN5V2jZ5ZlZFrok3U5rd_3IRcOM',
    appId: '1:736087562902:ios:d69192e0f55310458e40b7',
    messagingSenderId: '736087562902',
    projectId: 'interior-project-b5a35',
    storageBucket: 'interior-project-b5a35.firebasestorage.app',
    iosBundleId: 'com.example.interior-workcost-app',
  );
}
